<div class="col-sm-12">
    <div class="row">
        <div class="col-md-10">
        <?php $INFO=AUTHORITY::validateKey(KEY_INFO);  ?>
                    <h3>Laporan Data Kartu Stok <?= $INFO['data']->nama_toko?></h3>
                    <h4><?= $INFO['data']->alamat ." " .$INFO['data']->telp ?></h4>
                    <h5>Tanggal <?php echo date('d M Y') ?></h5>
            
        </div>
        <div class="col-md-2 ">
            <!-- <div class="pull-right">
                <a href="<?php echo base_url() ."laporan/barang/print" ?>" class="btn btn-default btn-xs" target="_blank"><span class="fa fa-print"></span></a>
                <a href="<?php echo base_url() ."laporan/barang/pdf" ?>" class="btn btn-danger btn-xs" target="_blank"><span class="fa fa-file-pdf-o"></span></a>
                <a href="<?php echo base_url() ."laporan/barang/excel" ?>" class="btn btn-success btn-xs" target="_blank"><span class="fa fa fa-file-excel-o"></span></a>
            </div> -->
            
        </div>
        <div class="col-md-12">
            <div class="col-md-12" style="border-top:double #000; border-collapse: collapse;border-width: 1px">&nbsp;</div>
        </div>
        
        <p>&nbsp;</p>
        
    </div>
    <?php if(!empty($list)){?>
    <table class="table table-bordered" >
        <tbody>
            <?php 
            $satuan=$barang_data->barang_satuan_kecil;
            if(!empty($stokawal)){
                $awal=$stokawal->jml_masuk - $stokawal->jml_keluar;
                
            }else $awal=0;
             ?>
            <th colspan="5">Sisa Stok Terakhir sampai tanggal <?= $dari ." Adalah " .$awal ." $satuan"  ?></th>
        </tbody>
        <thead class="bg-green">
            <tr>
                <th style="width: 10px;">No</th><th>Kode</th><th>Masuk</th><th>Keluar</th><th>Sisa</th>
            <tr>
        </thead>
        <tbody id="">
            <?php 
            $start=0;
            foreach ($list as $b) {
                $start++;
                $awal=$awal+$b->jml_masuk-$b->jml_keluar;
                echo "
                <tr>
                    <td style=\"width: 10px;\">" .$start ."</td>
                    <td>" .$b->barang_id ."</td>
                    <td>" .$b->jml_masuk ." $satuan</td>
                    <td>" .$b->jml_keluar ." $satuan</td>
                    <td>" .$awal ."</td>
                <tr>";
            }
            ?>
        </tbody>
        
    </table>
    <?php } ?>
    <div class="row">
        <div class="col-sm-12 pull-right" style="text-align: left;">
            <div id="nav"></div>
            <div id="curidx"></div>
        </div>
    </div>
    
</div>
<!--========================================================================================================
End of file barang_list.php 
Location: ./application/views/barang_list.php 
Please DO NOT modify this information : 
Generated by Codeigniter CRUD Generator V1 21 Oct 2017 07:12:17 
Copyright @ 2017 By Wanhar Azri S.Kom 
============================================================================================================-->